[package]
name = "carbonthrone-gui"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "carbonthrone_gui"
path = "src/main.rs"

[features]
dev = ["bevy-inspector-egui"]

[dependencies]
carbonthrone = { path = "../core" }
bevy = "0.18.1"
rand = "0.8"
bevy-inspector-egui = { version = "0.36", optional = true }
