[package]
name = "carbonthrone-gui"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "carbonthrone_gui"
path = "src/main.rs"

[features]
default = ["dev"]
dev = ["bevy-inspector-egui", "bevy_egui", "bevy/file_watcher", "bevy/asset_processor"]

[dependencies]
carbonthrone = { path = "../core" }
bevy = "0.18.1"
rand = "0.8"
bevy-inspector-egui = { version = "0.36", optional = true }
bevy_egui = { version = "0.39", optional = true }
bevy_yarnspinner = "0.8"
